name: docker test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt install docker-compose

      - name: build docker images
        run: docker-compose up -d --build

      - name: use default config
        run: docker cp docker/qq.yaml yunzai-bot:/app/Yunzai-Bot/config/config

      - name: run test script
        run: docker exec yunzai-bot npm run test
